language: ruby
before_install:
  - gem install bundler

bundler_args: --without development
cache:
  - bundler
  - apt

rvm:
  - 2.0
  - 2.1
  - 2.2.2
  - 2.3.0
  - jruby-9.0.0.0
  - ruby-head
services:
  - mongodb


gemfile:
  - gemfiles/mongoid3.gemfile
  - gemfiles/mongoid4.gemfile
  - gemfiles/mongoid5.gemfile
  - Gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.0
      gemfile: Gemfile
    - rvm: 2.1
      gemfile: Gemfile
