language: ruby
bundler_args: --without development
cache:
  - bundler
  - apt

rvm:
  - ruby-head
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - jruby-19mode
  - jruby-9.0.0.0
services:
  - mongodb
matrix:
  allow_failures:
    - rvm: ruby-head

gemfile:
  - Gemfile
  - gemfiles/mongoid3.gemfile
  - gemfiles/mongoid4.gemfile
